- VkLayer_profiler_layer/profiler/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.h
- VkLayer_profiler_layer/profiler/profiler_helpers.h
- VkLayer_profiler_layer/profiler/profiler_sync.cpp
- VkLayer_profiler_layer/profiler/profiler_sync.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
Description:
Send synchronization timestamps to all created device queues at the beginning of each frame for reference.
> Improve multiple queue handling

- .gitmodules
- CMakeLists.txt
- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_helpers.h
- VkLayer_profiler_layer/profiler/profiler_shader.h
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkAccelerationStructureKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkAccelerationStructureKhr_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkRayTracingPipelineKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkRayTracingPipelineKhr_functions.h
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_ex.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_ex.h
- VkLayer_profiler_layer/profiler_overlay/lang/en_us.h
- VkLayer_profiler_layer/profiler_overlay/lang/pl_pl.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_trace/profiler_json.cpp
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
Add support for VK_KHR_ray_query and VK_KHR_ray_tracing_pipeline extensions.
> Add ray tracing support.

- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkCommandBuffer_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkCommandBuffer_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDynamicRenderingKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDynamicRenderingKhr_functions.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
Add support for dynamicRendering feature (core 1.3) and VK_KHR_dynamic_rendering extension.
> Add dynamic rendering support.

- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkCommandBuffer_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkCommandBuffer_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSynchronization2Khr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSynchronization2Khr_functions.h
Add support for vkQueueSubmit2KHR and vkCmdPipelineBarrier2KHR and equivalent Vulkan 1.3 promoted functions.
> Add VK_KHR_synchronization2 support.

- .gitmodules
- External/CMakeLists.txt
- README.md
- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/VkLayer_profiler_layer.json.in
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_config.cpp
- VkLayer_profiler_layer/profiler/profiler_config.h
- VkLayer_profiler_layer/profiler/profiler_helpers.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkInstance_functions_base.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkPhysicalDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_objects/VkInstance_object.h
- VkLayer_profiler_layer/scripts/gen_config.py
Add layer settings to the layer manifest, so it can be configured with Vulkan Configurator and vk_layer_settings.txt.
> Add Vulkan layer settings extension support.

- VkLayer_profiler_layer/profiler_overlay/CMakeLists.txt
- VkLayer_profiler_layer/profiler_overlay/imgui_impl_xcb.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_impl_xlib.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_ex.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_ex.h
- VkLayer_profiler_layer/profiler_overlay/lang/en_us.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_settings.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_settings.h
Convert to ImGui docking branch to allow layout customization.
> Add docking windows.

- VkLayer_profiler_layer/profiler_overlay/lang/en_us.h
- VkLayer_profiler_layer/profiler_overlay/lang/pl_pl.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_settings.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_settings.h
Reduce height of the main window's toolbar to fit more data.
> Put profiled device name in the titlebar.

- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_helpers.h
- VkLayer_profiler_layer/profiler/profiler_stat_comparators.h
- VkLayer_profiler_layer/profiler_ext/VkProfilerEXT.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
Add support for nested secondary command buffers and subpasses with both inline contents and secondary command buffers.
> Add VK_EXT_nested_command_buffer support

- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler_overlay/lang/en_us.h
- VkLayer_profiler_layer/profiler_overlay/lang/pl_pl.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
Collect total, min, max and avg duration of each drawcall type.
Show the new statistics in a table.
Update ImGui.
> Add drawcall duration statistics.

- .gitmodules
- External/CMakeLists.txt
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.h
- VkLayer_profiler_layer/profiler_overlay/CMakeLists.txt
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_settings.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_settings.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_shader_view.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_shader_view.h
Allow users to save the current shader representation to file for offline analysis.
> Add option to save shader representation to file.

- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer_query_pool.h
- VkLayer_profiler_layer/profiler/profiler_counters.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_query_pool.cpp
- VkLayer_profiler_layer/profiler/profiler_sync.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkCommandBuffer_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkQueue_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkAccelerationStructureKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkCreateRenderPass2Khr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDeferredHostOperationsKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDrawIndirectCountAmd_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDrawIndirectCountKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDynamicRenderingKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkMeshShaderExt_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkMeshShaderNv_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkRayTracingPipelineKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkShaderObjectExt_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSwapchainKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSynchronization2Khr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_objects/VkDevice_object.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
- VkLayer_profiler_layer/profiler_trace/profiler_trace.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace_event.cpp
- VkLayer_profiler_layer/profiler_trace/profiler_trace_event.h
Measure and display the profiling overhead in the trace.
> Add counters for measuring time spent in profiler.

- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.h
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_histogram_ex.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_histogram_ex.h
- VkLayer_profiler_layer/profiler_overlay/lang/en_us.h
- VkLayer_profiler_layer/profiler_overlay/lang/pl_pl.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
Present queue utilization and show dependencies between command buffers on a graph.
> Add queue utilization graph.

- VkLayer_profiler_layer/profiler_overlay/imgui_impl_vulkan_layer.cpp
- VkLayer_profiler_layer/scripts/gen_dispatch_tables.py
ImGui uses the same function to get both device and instance functions. On some drivers vkGetDeviceProcAddr may return a non-null address of instance functions, leading to crashes in ImGui. Rewrite the function loader for ImGui to handle this behavior.
> Fix crash when vkGetDeviceProcAddr returns a non-null address of an instance function.

- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_shader_view.cpp
Embedded shaders may be split into multiple OpSourceContinued instructions. Concatenate them back into a single string.
> Add support for shader source continuations.

- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/VkLayer_profiler_layer.json.in
- VkLayer_profiler_layer/profiler_layer_functions/core/VkInstance_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkInstance_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkPhysicalDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkPhysicalDevice_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkToolingInfoExt_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkToolingInfoExt_functions.h
Report profiler tool properties.
> Add support for VK_EXT_tooling_info.

- VkLayer_profiler_layer/profiler_helpers/CMakeLists.txt
- VkLayer_profiler_layer/profiler_helpers/profiler_csv_helpers.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_csv_helpers.h
- VkLayer_profiler_layer/profiler_overlay/lang/en_us.h
- VkLayer_profiler_layer/profiler_overlay/lang/pl_pl.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
Apply filter to the displayed metrics as well.
Make filter case insensitive and add optimization flag.
Fix combo box and text input widths.
Add options to save, load and take counters snapshots for comparison.
> Improve performance counters viewer.

- VkLayer_profiler_layer/profiler/profiler_data.cpp
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkAccelerationStructureKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDebugMarkerExt_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkDebugUtilsExt_functions.cpp
Reduce risk of memory leak when passing acceleration structure build arguments.
> Refactor drawcall payload memory management.

- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/profiler/CMakeLists.txt
- VkLayer_profiler_layer/profiler/intel/profiler_metrics_api.cpp
- VkLayer_profiler_layer/profiler/intel/profiler_metrics_api.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_frontend.h
- VkLayer_profiler_layer/profiler_ext/VkProfilerEXT.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions_base.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions_base.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSwapchainKhr_functions.cpp
- VkLayer_profiler_layer/profiler_layer_objects/profiler_layer_frontend.cpp
- VkLayer_profiler_layer/profiler_layer_objects/profiler_layer_frontend.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_shader_view.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_shader_view.h
This is the first part of changes that separate the overlay from the profiled device.
> Add profiler frontend interface between the layer and the overlay.

- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_shader.cpp
- VkLayer_profiler_layer/profiler/profiler_shader.h
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_ex.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_ex.h
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_table_ex.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_table_ex.h
- VkLayer_profiler_layer/profiler_overlay/lang/en_us.h
- VkLayer_profiler_layer/profiler_overlay/lang/pl_pl.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
Provide additional data on the most contributing pipelines.
TODO:
> Print top pipelines in a table.

- VkLayer_profiler_layer/profiler_overlay/profiler_overlay_shader_view.cpp
Use custom tokenizer function to handle strings due to stack overflow in MSVC std::regex implementation.
> Fix regex stack overflow when tokenizing long strings in SPIR-V.

- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
Fix crash when debug markers are inserted inside dynamic render pass. Count clears and resolves in dynamic render passes based on rendering flags.
> Fix dynamic render passes instrumentation.

- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSwapchainKhr_functions.cpp
Don't initialize the overlay when swapchain is created on an unsupported surface.
> Fix crash when using unsupported WSI.
