- VkLayer_profiler_layer/profiler/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler/profiler_command_pool.cpp
- VkLayer_profiler_layer/profiler/profiler_command_pool.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler_ext/VkProfilerEXT.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions_base.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkPhysicalDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_objects/VkInstance_object.h
- VkLayer_profiler_layer/profiler_layer_objects/VkPhysicalDevice_object.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_tests/profiler_command_buffer_tests.cpp
- VkLayer_profiler_layer/profiler_tests/profiler_vulkan_state.h
- VkLayer_profiler_layer/utils/lockable_unordered_map.h
Query pools can be reset only on graphics or compute queues.
Closes #8
> Don't profile command buffers executed on transfer queues

- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler_ext/VkProfilerEXT.cpp
- VkLayer_profiler_layer/profiler_ext/VkProfilerEXT.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions_base.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSwapchainKhr_functions.cpp
Drop support for disabling profiler for specific devices (remove VK_PROFILER_CREATE_DISABLED_BIT_EXT flag).
Closes #7
> Return device functions via vkGetInstanceProcAddr

- VkLayer_profiler_layer/profiler/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler/profiler_command_buffer_query_pool.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer_query_pool.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.h
- VkLayer_profiler_layer/profiler/profiler_memory_manager.cpp
- VkLayer_profiler_layer/profiler/profiler_memory_manager.h
- VkLayer_profiler_layer/profiler/profiler_query_pool.cpp
- VkLayer_profiler_layer/profiler/profiler_query_pool.h
- VkLayer_profiler_layer/profiler_ext/VkProfilerEXT.cpp
- VkLayer_profiler_layer/profiler_helpers/profiler_data_helpers.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
Previously the profiler sampled always at the drawcall level. This introduced a significant overhead that rendered the per-pipeline and per-renderpass measurements unreliable. With new sampling modes, a high-level data can be obtained without impacting the performance of the measured regions.
This change implements already existing sampling modes that were present in VkProfilerExt.h:
- VK_PROFILER_MODE_PER_DRAWCALL_EXT (default)
- VK_PROFILER_MODE_PER_PIPELINE_EXT
- VK_PROFILER_MODE_PER_RENDER_PASS_EXT
- VK_PROFILER_MODE_PER_COMMAND_BUFFER_EXT
Sampling mode can be selected via environment variable VKPROF_SAMPLING_MODE: "DRAW", "PIPELINE", "RENDERPASS" or "COMMANDBUFFER".
> Add per pipeline, per render pass and per command buffer sampling modes.

- CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer_query_pool.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_helpers.h
- VkLayer_profiler_layer/profiler/profiler_query_pool.h
- VkLayer_profiler_layer/profiler/profiler_sync.cpp
- VkLayer_profiler_layer/profiler_layer_objects/VkObject.h
- VkLayer_profiler_layer/profiler_overlay/CMakeLists.txt
- VkLayer_profiler_layer/profiler_overlay/imgui_impl_xcb.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
- VkLayer_profiler_layer/profiler_trace/profiler_trace.h
- VkLayer_profiler_layer/utils/lockable_unordered_map.h
Add missing includes and wrap compiler extensions with macros.
Fix linking error on Linux when the profiled application uses ImGui.
Fix hangs on nvidia by temporarily disabling synchronization timestamps at the beginning of frame.
Use xcb_connection_has_error instead of checking m_Connection (which is always non-null).
> Fix compilation errors on Linux.

- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
Destroying a swapchain and creating a new one would simply cause a ton of dangling pointers and crashes.
Simply doing:
```cpp
vkCreateSwapchainKHR( ... );
vkGetSwapchainImagesKHR( ... );
render();
vkDestroySwapchainKHR( ... );
vkCreateSwapchainKHR( ... );
```
would trigger it.
This PR fixes it.
TBH the code follows some bad patterns, for example:
```cpp
if( (result == VK_SUCCESS) && (pCreateInfo->imageFormat != m_ImageFormat) )
{
if( m_RenderPass != VK_NULL_HANDLE )
{
// Destroy old render pass
m_pDevice->Callbacks.DestroyRenderPass( m_pDevice->Handle, m_RenderPass, nullptr );
}
...
}
```
Will never create `m_RenderPass` if it finds `pCreateInfo->imageFormat == m_ImageFormat`; even though `m_RenderPass` could be a null handle.
This PR doesn't address those issues, but it fixes what I …
> Fix crashes on Swapchain recreation

- CMakeLists.txt
- README.md
- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/VkLayer_profiler_layer.json.in
- VkLayer_profiler_layer/scripts/gen_licenses.py
Rename layer to "VK_LAYER_PROFILER_unified" so that the layer can be used with Vulkan Configurator.
Additionally:
- Generate list of licenses of all used external libraries automatically on install.
- Provide version of Vulkan headers used to build the layer.
> Rename the layer to match spec naming requirements.

- VkLayer_profiler_layer/profiler_layer_functions/Dispatch.h
Fixes the following compile error with g++ 13.2.0 (Ubuntu 23.10):
VulkanProfiler/VkLayer_profiler_layer/profiler_layer_functions/Dispatch.h:151:13: error: ‘hash’ is not a class template
Tests still fail to compile, but that is a separate issue.
> Fix compile error with g++ 13.2.0

- VkLayer_profiler_layer/profiler_overlay/imgui_impl_win32.cpp
- VkLayer_profiler_layer/profiler_overlay/imgui_impl_win32.h
Translate WM_KEYDOWN to WM_CHAR for keyboard input to work again.
Hook each window thread once to avoid receiving the same message multiple times if multiple windows are handled by the same thread.
> Fix Windows keyboard input.

- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_shader.h
- Use shared pointers to keep references to VkShaderModules in VkPipelines valid.
- Save shader module's bytecode for future features.
- Allow casting from DeviceProfilerPipelineData back to DeviceProfilerPipeline.
> Refactor VkShaderModule internal data structure.

- VkLayer_profiler_layer/CMakeLists.txt
- VkLayer_profiler_layer/VkLayer_profiler_layer.json.in
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/core/VkDevice_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkPipelineExecutablePropertiesKhr_functions.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkRayTracingPipelineKhr_functions.cpp
Enable VK_KHR_pipeline_executable_properties to request additional info on the pipeline shaders from the ICD.
> Add VK_KHR_pipeline_executable_properties support.

- VkLayer_profiler_layer/profiler/CMakeLists.txt
- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler/profiler_counters.h
- VkLayer_profiler_layer/profiler/profiler_counters_linux.inl
- VkLayer_profiler_layer/profiler/profiler_counters_windows.inl
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.h
- VkLayer_profiler_layer/profiler/profiler_sync.cpp
- VkLayer_profiler_layer/profiler/profiler_sync.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkQueue_functions.cpp
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkSynchronization2Khr_functions.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
- VkLayer_profiler_layer/profiler_trace/profiler_trace.h
Rewrite CPU counters to use QueryPerformanceCounter on Windows and monotonic timestamps on Linux.
> Use VK_EXT_calibrated_timestamps to synchronize CPU and GPU traces.

- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_command_buffer.h
- VkLayer_profiler_layer/profiler/profiler_command_pool.cpp
- VkLayer_profiler_layer/profiler/profiler_command_pool.h
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
Improve detection of queues that support timestamp query and don't aggregate data of command buffers submitted to queues that don't.
> Skip data from command buffers that were not instrumented.

- VkLayer_profiler_layer/profiler/profiler_command_buffer.cpp
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
Use UINT32_MAX instead of -1 to mark and check for internally inserted subpasses, that handle commands outside of render pass scope.
Refactor PrintDuration calls and remove redundant call in PrintCommandBuffer.
> Fix implicit subpass indexing.

- CMake/compiler.cmake
- CMake/compiler_linux.cmake
- CMake/compiler_windows.cmake
- CMake/platform_linux.cmake
- CMakeLists.txt
X11 library must be imported after calling project() in cmake.
> Fix missing xlib support.

- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler_layer_functions/extensions/VkRayTracingPipelineKhr_functions.cpp
- VkLayer_profiler_layer/profiler_tests/CMakeLists.txt
- VkLayer_profiler_layer/profiler_tests/profiler_extensions_tests.cpp
- VkLayer_profiler_layer/profiler_tests/profiler_vulkan_simple_triangle.h
- VkLayer_profiler_layer/profiler_tests/profiler_vulkan_simple_triangle_rt.h
- VkLayer_profiler_layer/profiler_tests/profiler_vulkan_state.h
- VkLayer_profiler_layer/profiler_tests/shaders/CMakeLists.txt
- VkLayer_profiler_layer/profiler_tests/shaders/simple_triangle.frag.glsl
- VkLayer_profiler_layer/profiler_tests/shaders/simple_triangle.vert.glsl
- VkLayer_profiler_layer/profiler_tests/shaders/simple_triangle_rt.rchit.glsl
- VkLayer_profiler_layer/profiler_tests/shaders/simple_triangle_rt.rgen.glsl
- VkLayer_profiler_layer/profiler_tests/shaders/simple_triangle_rt.rmiss.glsl
- VkLayer_profiler_layer/utils/lockable_unordered_map.h
Use insert_or_assign instead of emplace to allow overriding existing default names with names provided by the application.
> Fix missing pipeline object names.

- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
Encountered a crash while profiling the game 'Enshrouded', the crash was a nullptr exception inside the `std::string_view` constructor because it's trying to get the length of the string but since that's a nullptr, the call fails.
> Fix crash in case a debug label has a nullptr as name

- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
Check for empty string before calling pop_back on it.
> Fix crash when top pipeline name is entirely elided.

- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.cpp
- VkLayer_profiler_layer/profiler_overlay/profiler_overlay.h
Clicking on a command buffer in the queue graph will now scroll to that command buffer in the frame browser. Queue graph tooltips will now show command buffer name and duration.
> Jump to selected command buffer from the queue graph.

- VkLayer_profiler_layer/profiler_overlay/imgui_widgets/imgui_histogram_ex.cpp
Closing a combo box or a modal window displayed on top of the performance graph should not trigger a mouse click in the graph if the cursor is over it.
> Fix performance graph mouse events.

- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler_data.h
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.cpp
- VkLayer_profiler_layer/profiler/profiler_data_aggregator.h
- VkLayer_profiler_layer/profiler_trace/profiler_trace.cpp
Send synchronization timestamps before the submission to avoid integer overflows and don't insert vkQueuePresentKHR events in per-submit traces.
> Fix traces collected in per-submit mode.

- VkLayer_profiler_layer/profiler/profiler.cpp
- VkLayer_profiler_layer/profiler/profiler.h
- VkLayer_profiler_layer/profiler_layer_functions/core/VkInstance_functions.cpp
The extension is an instance extension, so it should be checked and implicitly enabled during instance creation.
> Fix VK_KHR_get_physical_device_properties2 extension enabling.

- VkLayer_profiler_layer/profiler/profiler_memory_tracker.cpp
- VkLayer_profiler_layer/profiler_tests/profiler_command_buffer_tests.cpp
- VkLayer_profiler_layer/profiler_tests/profiler_memory_tests.cpp
- VkLayer_profiler_layer/profiler_tests/profiler_testing_common.h
- VkLayer_profiler_layer/profiler_tests/profiler_vulkan_state.h
When memory is a null handle, the specified region is unbound.
> Fix incorrect handling of null memory in sparse buffer binding.
